// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_tdd/test/mockito_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_tdd/custom_test.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Counter].
///
/// See the documentation for Mockito's code generation for more information.
class MockCounter extends _i1.Mock implements _i2.Counter {
  MockCounter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: 0,
      ) as int);
  @override
  set value(int? _value) => super.noSuchMethod(
        Invocation.setter(
          #value,
          _value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  void add() => super.noSuchMethod(
        Invocation.method(
          #add,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
